import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("engineer")
  .setShaped([
    [<botania:storage:4>, <forbidden_arcanus:arcane_gold_ingot>, <forbidden_arcanus:arcane_gold_ingot>, <forbidden_arcanus:arcane_gold_ingot>, <botania:storage:4>],
    [<forbidden_arcanus:arcane_gold_ingot>, <minecraft:skull:3>.withTag({HideFlags: 5, SkullOwner: {Id: "b961514a-7619-43d4-a019-73227510aa2f", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDM5OWM5NzNkNjQ5NmQxZDI1ODQ5MmMyOGQ0Yzk1OTU2YWMzYTI1Mzc2MmJmMTVmNzY0NGFmMWY1NzI4ZGQifX19"}]}}, display: {Name: "§eWolf Fragment"}}), <minecraft:skull:3>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 1, SkullOwner: {Id: "7c3c5222-2aca-47c0-a1fc-493fec60f166", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmY4OWIxNTBiZTljNGM1MjQ5ZjM1NWY2OGVhMGM0MzkxMzAwYTliZTFmMjYwZDc1MGZjMzVhMTgxN2FkNzk2ZSJ9fX0="}]}}, display: {Name: "§eSuperior Dragon Fragment"}}), <minecraft:skull:3>.withTag({HideFlags: 5, SkullOwner: {Id: "b961514a-7619-43d4-a019-73227510aa2f", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDM5OWM5NzNkNjQ5NmQxZDI1ODQ5MmMyOGQ0Yzk1OTU2YWMzYTI1Mzc2MmJmMTVmNzY0NGFmMWY1NzI4ZGQifX19"}]}}, display: {Name: "§eWolf Fragment"}}), <forbidden_arcanus:arcane_gold_ingot>],
    [<forbidden_arcanus:arcane_gold_ingot>, <minecraft:skull:3>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 1, SkullOwner: {Id: "7c3c5222-2aca-47c0-a1fc-493fec60f166", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmY4OWIxNTBiZTljNGM1MjQ5ZjM1NWY2OGVhMGM0MzkxMzAwYTliZTFmMjYwZDc1MGZjMzVhMTgxN2FkNzk2ZSJ9fX0="}]}}, display: {Name: "§eSuperior Dragon Fragment"}}), <forbidden_arcanus:dark_nether_star>, <minecraft:skull:3>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 1, SkullOwner: {Id: "7c3c5222-2aca-47c0-a1fc-493fec60f166", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmY4OWIxNTBiZTljNGM1MjQ5ZjM1NWY2OGVhMGM0MzkxMzAwYTliZTFmMjYwZDc1MGZjMzVhMTgxN2FkNzk2ZSJ9fX0="}]}}, display: {Name: "§eSuperior Dragon Fragment"}}), <forbidden_arcanus:arcane_gold_ingot>],
    [<forbidden_arcanus:arcane_gold_ingot>, <minecraft:skull:3>.withTag({HideFlags: 5, SkullOwner: {Id: "b961514a-7619-43d4-a019-73227510aa2f", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDM5OWM5NzNkNjQ5NmQxZDI1ODQ5MmMyOGQ0Yzk1OTU2YWMzYTI1Mzc2MmJmMTVmNzY0NGFmMWY1NzI4ZGQifX19"}]}}, display: {Name: "§eWolf Fragment"}}), <minecraft:skull:3>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 1, SkullOwner: {Id: "7c3c5222-2aca-47c0-a1fc-493fec60f166", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmY4OWIxNTBiZTljNGM1MjQ5ZjM1NWY2OGVhMGM0MzkxMzAwYTliZTFmMjYwZDc1MGZjMzVhMTgxN2FkNzk2ZSJ9fX0="}]}}, display: {Name: "§eSuperior Dragon Fragment"}}), <minecraft:skull:3>.withTag({HideFlags: 5, SkullOwner: {Id: "b961514a-7619-43d4-a019-73227510aa2f", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDM5OWM5NzNkNjQ5NmQxZDI1ODQ5MmMyOGQ0Yzk1OTU2YWMzYTI1Mzc2MmJmMTVmNzY0NGFmMWY1NzI4ZGQifX19"}]}}, display: {Name: "§eWolf Fragment"}}), <forbidden_arcanus:arcane_gold_ingot>],
    [<botania:storage:4>, <forbidden_arcanus:arcane_gold_ingot>, <forbidden_arcanus:arcane_gold_ingot>, <forbidden_arcanus:arcane_gold_ingot>, <botania:storage:4>]])
  .addOutput(<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}))
  .create();

RecipeBuilder.get("engineer")
  .setShaped([
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})],
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), null, <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})]])
  .addOutput(<minecraft:skull:3>.withTag({HideFlags: 3, SkullOwner: {Id: "b48196b0-b6e2-4f6e-a774-91cc09d1d1d1", Properties: {textures: [{Value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQ2NDljNmMyMmNiMjQ4MGExNDAwZmI3ZTg0NWJkZGYzNmZmY2QzMDExZGQ1MWE4ZTlhYWJlYmVhZTkxOGJiNiJ9fX0="}]}}, display: {Lore: ["§7Health: §a+34HP", "§7Defence: §a+43", "§7Crit Damage: §a+200%", "", "§b§lGRAND HELMET"], Name: "§4§lMarkWolf Helmet "}, AttributeModifiers: [{UUIDMost: -857776929822653057 as long, UUIDLeast: -6213342835983419951 as long, Amount: 34.0, Slot: "head", AttributeName: "generic.maxHealth", Operation: 0, Name: "generic.maxHealth"}, {UUIDMost: 7686867814618907140 as long, UUIDLeast: -8913212101395605724 as long, Amount: 43.0, Slot: "head", AttributeName: "generic.armor", Operation: 0, Name: "generic.armor"}, {UUIDMost: -2438934718384288566 as long, UUIDLeast: -5163230248013458585 as long, Amount: 2.0, Slot: "head", AttributeName: "generic.attackDamage", Operation: 1, Name: "generic.attackDamage"}]}))
  .create();

  RecipeBuilder.get("engineer")
  .setShaped([
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), null, <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})],
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})],
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})]])
  .addOutput(<minecraft:leather_chestplate>.withTag({Unbreakable: 1 as byte, HideFlags: 7, display: {Lore: ["§7Health: §a+54HP", "§7Defence; §a+45", "§7Speed: §a+50%", "", "§b§lGRAND CHESTPLATE"], color: 6946816, Name: "§4§lMarkWolf Chestplate"}, AttributeModifiers: [{UUIDMost: -8684803822366736002 as long, UUIDLeast: -7829281074006135160 as long, Amount: 54.0, Slot: "chest", AttributeName: "generic.maxHealth", Operation: 0, Name: "generic.maxHealth"}, {UUIDMost: 2867584797141778845 as long, UUIDLeast: -7161514895229124682 as long, Amount: 45.0, Slot: "chest", AttributeName: "generic.armor", Operation: 0, Name: "generic.armor"}, {UUIDMost: -3773480177342921451 as long, UUIDLeast: -7939619924859788827 as long, Amount: 0.5, Slot: "chest", AttributeName: "generic.movementSpeed", Operation: 1, Name: "generic.movementSpeed"}]}))
  .create();

  RecipeBuilder.get("engineer")
  .setShaped([
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})],
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), null, <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})],
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), null, <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})]])
  .addOutput(<minecraft:leather_leggings>.withTag({Unbreakable: 1 as byte, HideFlags: 7, display: {Lore: ["§7Health:§a +37HP", "§7Defence:§a +41", "§7Attack Speed: §a+60%", "", "§b§lGRAND LEGGINGS"], color: 7012352, Name: "§4§lMarkWolf Leggings"}, AttributeModifiers: [{UUIDMost: 2699327112761458796 as long, UUIDLeast: -5789286445385512833 as long, Amount: 37.0, Slot: "legs", AttributeName: "generic.maxHealth", Operation: 0, Name: "generic.maxHealth"}, {UUIDMost: 8580854211819292292 as long, UUIDLeast: -5451746082710167298 as long, Amount: 41.0, Slot: "legs", AttributeName: "generic.armor", Operation: 0, Name: "generic.armor"}, {UUIDMost: -1457435804997433678 as long, UUIDLeast: -7624172609819206541 as long, Amount: 0.6, Slot: "legs", AttributeName: "generic.attackSpeed", Operation: 1, Name: "generic.attackSpeed"}]}))
  .create();

  RecipeBuilder.get("engineer")
  .setShaped([
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), null, <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})],
    [<minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}}), null, <minecraft:firework_charge>.withTag({ench: [{lvl: 1 as short, id: 31 as short}], HideFlags: 37, display: {Lore: ["", "§7A condensed piece of wolf and dragon.", "", "§b§lGRAND ITEM", ""], Name: "§5Mark Receptor."}})]])
  .addOutput(<minecraft:leather_boots>.withTag({cloud: 36, Unbreakable: 1 as byte, HideFlags: 7, display: {Lore: ["§7Health: §a+32HP", "§7Defence: §a+45", "§7Speed: §a+100%", "", "§b§lGRAND BOOTS"], color: 7012352, Name: "§4§lMarkWolf Boots"}, AttributeModifiers: [{UUIDMost: -2952145218974757684 as long, UUIDLeast: -5563784414482820574 as long, Amount: 32.0, Slot: "feet", AttributeName: "generic.maxHealth", Operation: 0, Name: "generic.maxHealth"}, {UUIDMost: 7806500611158917941 as long, UUIDLeast: -7331480937584902072 as long, Amount: 45.0, Slot: "feet", AttributeName: "generic.armor", Operation: 0, Name: "generic.armor"}, {UUIDMost: 611448599917641733 as long, UUIDLeast: -6956540695705997400 as long, Amount: 1.0, Slot: "feet", AttributeName: "generic.movementSpeed", Operation: 1, Name: "generic.movementSpeed"}], launchuses: 0}))
  .create();

  
